### ISSUE TITLE
Tray does not start automatically after setup

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#68]
### General information

Tested on downstream environments 

## CRC version
```bash
CodeReady Containers version: 1.26.0+31f06c09
OpenShift version: 4.7.8 (embedded in executable)
```

## CRC config
```bash
- consent-telemetry                     : no
- enable-experimental-features          : true
- pull-secret-file                      :XXXX
```

### Steps to reproduce

  1. Install CRC from msi installer 
  2. crc setup

### Expected

Setup is complete properly and tray is started

### Actual

Randomly got error around the daemon (showed in the picture), logs did not show any error. Then after setup finish with or without error tray process never start. 

![126-windows-daemon-start-error](https://user-images.githubusercontent.com/1957899/117117191-8ba97800-ad8f-11eb-9cb6-d8e22c992110.png)

As a workaround tray can be started manually double clicking on the tray.exe.

### Logs

```bash
INFO Checking if admin-helper executable is cached
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
INFO Checking if running in a shell with administrator rights
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
INFO Checking if tray executable is present
INFO Checking if CodeReady Containers daemon is installed
INFO Installing CodeReady Containers daemon
INFO Will run as admin: Create symlink to daemon batch file in start-up folder
INFO Checking if tray is installed
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\crcqe\.crc\cache\crc_hyperv_4.7.8.crcbundle exists
Your system is correctly setup for using CodeReady Containers, you can now run 'crc start' to start the OpenShift cluster
```

**Comment by anjannath** [comment]
It was attempted to be fixed by introducing a sleep after calling the start daemon function, giving it time to start. https://github.com/code-ready/tray-windows/blob/f7c32006f6bc8e5ac301bfe628b37f9925f140c0/Program.cs#L62-L65 the sleep time is needed since we are doing `crc setup --check-only` when the daemon starts. During the sleep period, the menu won't show when user clicks on the icon. 
we could delay the call to the daemon till when user first clicks on a menuitem and still show the menu, but if user clicks on it before that "time" he'll see an error, its better to not show the menu at all in that case, and only show it when actions are possible.

during this sleep period we need to convey to the user that something is happening in the background by animating the icon or at least change the cursor to a busy state cursor.

**Comment by anjannath** [comment]
Should not be an issue now, feel free to reopen if this is still the case
